apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: olaidehok/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: 'src/**/*.js'
        - image: olaidehok/comments
          context: comments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '*.js'
        - image: olaidehok/event-bus
          context: event-bus
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '*.js'
        - image: olaidehok/moderation
          context: moderation
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '*.js'
        - image: olaidehok/posts
          context: posts
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '*.js'
        - image: olaidehok/query
          context: query
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '*.js'
